//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showcase.InventoryManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Showcase.InventoryManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name - Company Name.
        /// </summary>
        internal static string AppointmentText {
            get {
                return ResourceManager.GetString("AppointmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contact Name.
        /// </summary>
        internal static string CompanyContactName {
            get {
                return ResourceManager.GetString("CompanyContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Customers___Gray___36x36 {
            get {
                object obj = ResourceManager.GetObject("Customers___Gray___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers___White___36x36 {
            get {
                object obj = ResourceManager.GetObject("Customers___White___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_116x116 {
            get {
                object obj = ResourceManager.GetObject("Customers_116x116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_Export___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_Export___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_Export___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_Export___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_FullList___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_FullList___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_FullList___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_FullList___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_NewCustomer___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_NewCustomer___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_NewCustomer___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_NewCustomer___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_NewSupplier___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_NewSupplier___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customers_NewSupplier___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Customers_NewSupplier___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Orders Schedule.
        /// </summary>
        internal static string DailyOrdersSchedule {
            get {
                return ResourceManager.GetString("DailyOrdersSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the product.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Home___Gray___36x36 {
            get {
                object obj = ResourceManager.GetObject("Home___Gray___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home___White___36x36 {
            get {
                object obj = ResourceManager.GetObject("Home___White___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home_NewProduct {
            get {
                object obj = ResourceManager.GetObject("Home_NewProduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory___Gray___36x36 {
            get {
                object obj = ResourceManager.GetObject("Inventory___Gray___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory___White___36x36 {
            get {
                object obj = ResourceManager.GetObject("Inventory___White___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_116x116 {
            get {
                object obj = ResourceManager.GetObject("Inventory_116x116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_AddNewProduct___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_AddNewProduct___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_AddNewProduct___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_AddNewProduct___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_ExportProduct___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_ExportProduct___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_ExportProduct___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_ExportProduct___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_ImportProduct___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_ImportProduct___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_ImportProduct___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_ImportProduct___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_Product___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_Product___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_Product___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Inventory_Product___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Orders Schedule.
        /// </summary>
        internal static string MonthlyOrdersSchedule {
            get {
                return ResourceManager.GetString("MonthlyOrdersSchedule", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MoreActivityIndicator_Down {
            get {
                object obj = ResourceManager.GetObject("MoreActivityIndicator_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoreActivityIndicator_Up {
            get {
                object obj = ResourceManager.GetObject("MoreActivityIndicator_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NavigationArrow___Next___16x16 {
            get {
                object obj = ResourceManager.GetObject("NavigationArrow___Next___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigationArrow___Previous___16x16 {
            get {
                object obj = ResourceManager.GetObject("NavigationArrow___Previous___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders___Gray___36x36 {
            get {
                object obj = ResourceManager.GetObject("Orders___Gray___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders___White___36x36 {
            get {
                object obj = ResourceManager.GetObject("Orders___White___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_116x116 {
            get {
                object obj = ResourceManager.GetObject("Orders_116x116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Daily___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Daily___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Daily___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Daily___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Monthly___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Monthly___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Monthly___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Monthly___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Weekly___Color___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Weekly___Color___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orders_Weekly___White___16x16 {
            get {
                object obj = ResourceManager.GetObject("Orders_Weekly___White___16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order.
        /// </summary>
        internal static string ProductOrder {
            get {
                return ResourceManager.GetString("ProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Reports___Gray___36x36 {
            get {
                object obj = ResourceManager.GetObject("Reports___Gray___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reports___White___36x36 {
            get {
                object obj = ResourceManager.GetObject("Reports___White___36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reports_116x116 {
            get {
                object obj = ResourceManager.GetObject("Reports_116x116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Orders Schedule.
        /// </summary>
        internal static string WeeklyOrdersSchedule {
            get {
                return ResourceManager.GetString("WeeklyOrdersSchedule", resourceCulture);
            }
        }
    }
}
