//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showcase.INGear.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Showcase.INGear.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batteries.
        /// </summary>
        internal static string Batteries {
            get {
                return ResourceManager.GetString("Batteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Batteries_Battery {
            get {
                return ResourceManager.GetString("Batteries_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolts.
        /// </summary>
        internal static string Batteries_Bolts {
            get {
                return ResourceManager.GetString("Batteries_Bolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cables.
        /// </summary>
        internal static string Batteries_Cables {
            get {
                return ResourceManager.GetString("Batteries_Cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamps.
        /// </summary>
        internal static string Batteries_Clamps {
            get {
                return ResourceManager.GetString("Batteries_Clamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakes.
        /// </summary>
        internal static string Brakes {
            get {
                return ResourceManager.GetString("Brakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cables.
        /// </summary>
        internal static string Brakes_Cables {
            get {
                return ResourceManager.GetString("Brakes_Cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calipers.
        /// </summary>
        internal static string Brakes_Calipers {
            get {
                return ResourceManager.GetString("Brakes_Calipers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discs.
        /// </summary>
        internal static string Brakes_Discs {
            get {
                return ResourceManager.GetString("Brakes_Discs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drums.
        /// </summary>
        internal static string Brakes_Drums {
            get {
                return ResourceManager.GetString("Brakes_Drums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        internal static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternators.
        /// </summary>
        internal static string Engine_Alternators {
            get {
                return ResourceManager.GetString("Engine_Alternators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Blocks.
        /// </summary>
        internal static string Engine_Blocks {
            get {
                return ResourceManager.GetString("Engine_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolts.
        /// </summary>
        internal static string Engine_Bolts {
            get {
                return ResourceManager.GetString("Engine_Bolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaskets.
        /// </summary>
        internal static string Engine_Gaskets {
            get {
                return ResourceManager.GetString("Engine_Gaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulleys.
        /// </summary>
        internal static string Engine_Pulleys {
            get {
                return ResourceManager.GetString("Engine_Pulleys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Covers.
        /// </summary>
        internal static string Engine_ValveCovers {
            get {
                return ResourceManager.GetString("Engine_ValveCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Pumps.
        /// </summary>
        internal static string Engine_WaterPumps {
            get {
                return ResourceManager.GetString("Engine_WaterPumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand for Inventory Filter.
        /// </summary>
        internal static string ExpandInventoryFilter {
            get {
                return ResourceManager.GetString("ExpandInventoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER PART.
        /// </summary>
        internal static string OrderPart {
            get {
                return ResourceManager.GetString("OrderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Deliveries.
        /// </summary>
        internal static string PendingDeliveries {
            get {
                return ResourceManager.GetString("PendingDeliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistons.
        /// </summary>
        internal static string Pistons {
            get {
                return ResourceManager.GetString("Pistons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearings.
        /// </summary>
        internal static string Pistons_Bearings {
            get {
                return ResourceManager.GetString("Pistons_Bearings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Pump.
        /// </summary>
        internal static string Pistons_OilPump {
            get {
                return ResourceManager.GetString("Pistons_OilPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        internal static string Pistons_Rings {
            get {
                return ResourceManager.GetString("Pistons_Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Item.
        /// </summary>
        internal static string PricePerItem {
            get {
                return ResourceManager.GetString("PricePerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark Plugs.
        /// </summary>
        internal static string Spark_Plugs {
            get {
                return ResourceManager.GetString("Spark_Plugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string Sparkplugs_Boots {
            get {
                return ResourceManager.GetString("Sparkplugs_Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugs.
        /// </summary>
        internal static string Sparkplugs_Plugs {
            get {
                return ResourceManager.GetString("Sparkplugs_Plugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        internal static string Sparkplugs_Terminals {
            get {
                return ResourceManager.GetString("Sparkplugs_Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wires.
        /// </summary>
        internal static string Sparkplugs_Wires {
            get {
                return ResourceManager.GetString("Sparkplugs_Wires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension.
        /// </summary>
        internal static string Suspension {
            get {
                return ResourceManager.GetString("Suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shocks.
        /// </summary>
        internal static string Suspension_Shocks {
            get {
                return ResourceManager.GetString("Suspension_Shocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struts.
        /// </summary>
        internal static string Suspension_Struts {
            get {
                return ResourceManager.GetString("Suspension_Struts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires.
        /// </summary>
        internal static string Tires {
            get {
                return ResourceManager.GetString("Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Weather.
        /// </summary>
        internal static string Tires_AllWeather {
            get {
                return ResourceManager.GetString("Tires_AllWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Tires_Snow {
            get {
                return ResourceManager.GetString("Tires_Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Tires_Standard {
            get {
                return ResourceManager.GetString("Tires_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due.
        /// </summary>
        internal static string TotalDue {
            get {
                return ResourceManager.GetString("TotalDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight (lbs).
        /// </summary>
        internal static string TotalWeightLbs {
            get {
                return ResourceManager.GetString("TotalWeightLbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        internal static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmissions.
        /// </summary>
        internal static string Transmissions {
            get {
                return ResourceManager.GetString("Transmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Transmissions_Automatic {
            get {
                return ResourceManager.GetString("Transmissions_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Transmissions_Manual {
            get {
                return ResourceManager.GetString("Transmissions_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW SHIPMENT.
        /// </summary>
        internal static string ViewShipment {
            get {
                return ResourceManager.GetString("ViewShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (lbs).
        /// </summary>
        internal static string WeightLbs {
            get {
                return ResourceManager.GetString("WeightLbs", resourceCulture);
            }
        }
    }
}
