//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showcase.CashflowDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Showcase.CashflowDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        internal static string CashflowDetails_Category_Label_current {
            get {
                return ResourceManager.GetString("CashflowDetails_Category_Label_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        internal static string CashflowDetails_Category_Label_lastmonth {
            get {
                return ResourceManager.GetString("CashflowDetails_Category_Label_lastmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        internal static string CashflowDetails_Category_Label_lastyear {
            get {
                return ResourceManager.GetString("CashflowDetails_Category_Label_lastyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string CashflowDetails_Category_Label_noPreviousData {
            get {
                return ResourceManager.GetString("CashflowDetails_Category_Label_noPreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_label {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_last_month {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_last_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_last_year {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_last_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projected.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_projected {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_projected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_Source {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string CashflowDetails_Grid_Caption_value {
            get {
                return ResourceManager.GetString("CashflowDetails_Grid_Caption_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM.
        /// </summary>
        internal static string Chart_XAxis_Month_Format {
            get {
                return ResourceManager.GetString("Chart_XAxis_Month_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM yyyy.
        /// </summary>
        internal static string Chart_XAxis_Month_Format_January {
            get {
                return ResourceManager.GetString("Chart_XAxis_Month_Format_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}-{2}/{3}.
        /// </summary>
        internal static string DateRangeFormat {
            get {
                return ResourceManager.GetString("DateRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inflow {0}.
        /// </summary>
        internal static string InflowLabel_Text {
            get {
                return ResourceManager.GetString("InflowLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string MillionsSuffix {
            get {
                return ResourceManager.GetString("MillionsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outflow {0}.
        /// </summary>
        internal static string OutflowLabel_Text {
            get {
                return ResourceManager.GetString("OutflowLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to financing.
        /// </summary>
        internal static string Source_Text_Financing {
            get {
                return ResourceManager.GetString("Source_Text_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investing.
        /// </summary>
        internal static string Source_Text_Investing {
            get {
                return ResourceManager.GetString("Source_Text_Investing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operations.
        /// </summary>
        internal static string Source_Text_Operations {
            get {
                return ResourceManager.GetString("Source_Text_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string Source_Text_Other {
            get {
                return ResourceManager.GetString("Source_Text_Other", resourceCulture);
            }
        }
    }
}
