//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTune.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTune.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Name.
        /// </summary>
        internal static string AlbumName {
            get {
                return ResourceManager.GetString("AlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country News.
        /// </summary>
        internal static string CountryNews {
            get {
                return ResourceManager.GetString("CountryNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Downloads.
        /// </summary>
        internal static string MonthlyDownloads {
            get {
                return ResourceManager.GetString("MonthlyDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        internal static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop News.
        /// </summary>
        internal static string PopNews {
            get {
                return ResourceManager.GetString("PopNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R &amp; B.
        /// </summary>
        internal static string RAndB {
            get {
                return ResourceManager.GetString("RAndB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R &amp; B News.
        /// </summary>
        internal static string RBNews {
            get {
                return ResourceManager.GetString("RBNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock News.
        /// </summary>
        internal static string RockNews {
            get {
                return ResourceManager.GetString("RockNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Grossing Artists.
        /// </summary>
        internal static string TopGrossingArtists {
            get {
                return ResourceManager.GetString("TopGrossingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Performing Artists.
        /// </summary>
        internal static string TopPerformingArtists {
            get {
                return ResourceManager.GetString("TopPerformingArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads.
        /// </summary>
        internal static string TotalDownloads {
            get {
                return ResourceManager.GetString("TotalDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks sold.
        /// </summary>
        internal static string TracksSold {
            get {
                return ResourceManager.GetString("TracksSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks sold this month.
        /// </summary>
        internal static string TracksSoldThisMonth {
            get {
                return ResourceManager.GetString("TracksSoldThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Title.
        /// </summary>
        internal static string TrackTitle {
            get {
                return ResourceManager.GetString("TrackTitle", resourceCulture);
            }
        }
    }
}
