//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elemental.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elemental.Assets.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Foliage.
        /// </summary>
        internal static string AbstractFoliage {
            get {
                return ResourceManager.GetString("AbstractFoliage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Waves Surfing.
        /// </summary>
        internal static string BigWavesSurfing {
            get {
                return ResourceManager.GetString("BigWavesSurfing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Dragon.
        /// </summary>
        internal static string BlackDragon {
            get {
                return ResourceManager.GetString("BlackDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column axis.
        /// </summary>
        internal static string ColumnDropAreaText {
            get {
                return ResourceManager.GetString("ColumnDropAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE FILTER.
        /// </summary>
        internal static string DateFilter {
            get {
                return ResourceManager.GetString("DateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Rider.
        /// </summary>
        internal static string FastRider {
            get {
                return ResourceManager.GetString("FastRider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No filters].
        /// </summary>
        internal static string FilterDropAreaText {
            get {
                return ResourceManager.GetString("FilterDropAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  HOODED COLLECTION.
        /// </summary>
        internal static string HoodedCollection {
            get {
                return ResourceManager.GetString("HoodedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        internal static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3.
        /// </summary>
        internal static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q4.
        /// </summary>
        internal static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock &amp; Roll.
        /// </summary>
        internal static string RockAndRoll {
            get {
                return ResourceManager.GetString("RockAndRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Star.
        /// </summary>
        internal static string RockStar {
            get {
                return ResourceManager.GetString("RockStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row axis.
        /// </summary>
        internal static string RowDropAreaText {
            get {
                return ResourceManager.GetString("RowDropAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3167A.
        /// </summary>
        internal static string SKU3167A {
            get {
                return ResourceManager.GetString("SKU3167A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3650A.
        /// </summary>
        internal static string SKU3650A {
            get {
                return ResourceManager.GetString("SKU3650A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4589A.
        /// </summary>
        internal static string SKU4589A {
            get {
                return ResourceManager.GetString("SKU4589A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6309A.
        /// </summary>
        internal static string SKU6309A {
            get {
                return ResourceManager.GetString("SKU6309A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6917A.
        /// </summary>
        internal static string SKU6917A {
            get {
                return ResourceManager.GetString("SKU6917A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7188A.
        /// </summary>
        internal static string SKU7188A {
            get {
                return ResourceManager.GetString("SKU7188A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8711A.
        /// </summary>
        internal static string SKU8711A {
            get {
                return ResourceManager.GetString("SKU8711A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9002A.
        /// </summary>
        internal static string SKU9002A {
            get {
                return ResourceManager.GetString("SKU9002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skulls &amp; Flourishes.
        /// </summary>
        internal static string SkullsAndFlourishes {
            get {
                return ResourceManager.GetString("SkullsAndFlourishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style #.
        /// </summary>
        internal static string SkuPrefix {
            get {
                return ResourceManager.GetString("SkuPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tattoo Love.
        /// </summary>
        internal static string TattooLove {
            get {
                return ResourceManager.GetString("TattooLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental Sales Dashboard.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VINTAGE ROCK.
        /// </summary>
        internal static string VintageRock {
            get {
                return ResourceManager.GetString("VintageRock", resourceCulture);
            }
        }
    }
}
